routes/web.php
<?php

use App\Http\Controllers\Frontend\CategoryController;
use App\Http\Controllers\Frontend\EmployeeController;
use App\Http\Controllers\Frontend\PostController;
use Illuminate\Support\Facades\Route;

Auth::routes([
    'reset' => false,
    'confirm' => false,
]);

Route::middleware(['auth:web', 'role:manager|employee'])->group(function () {
    Route::get('/', [PostController::class, 'index'])->name('main');
    Route::post('/posts/{model}/remove-image', [PostController::class, 'removeImage'])->name('posts.remove_image');
    Route::resource('/posts', PostController::class)->except('show')->parameter('posts', 'model');

    Route::resource('/categories', CategoryController::class)->except('show')->parameter('categories', 'model');

    Route::middleware('role:manager')->group(function () {
        Route::resource('/employees', EmployeeController::class)->except('show')->parameter('employees', 'model');
    });
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Image\Manipulations;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Post extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia;

    protected $fillable = [
        'category_id',
        'title',
    ];

    protected $hidden = [
        'user_id',
    ];

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('image')
            ->acceptsMimeTypes([
                'image/jpeg',
                'image/png',
                'image/svg',
                'image/svg+xml',
            ])
            ->singleFile();
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('xs')
            ->crop(Manipulations::CROP_CENTER, 50, 50)
            ->performOnCollections('image')
            ->nonQueued();

        $this->addMediaConversion('sm')
            ->crop(Manipulations::CROP_CENTER, 240, 150)
            ->performOnCollections('image')
            ->nonQueued();

        $this->addMediaConversion('md')
            ->fit(Manipulations::FIT_CONTAIN, 900, 900)
            ->performOnCollections('image')
            ->nonQueued();
    }

    public function user()
    {
        return $this->belongsTo(User::class)->withDefault();
    }

    public function category()
    {
        return $this->belongsTo(Category::class)->withDefault();
    }

    public function scopeCategory($query, $category_id = null)
    {
        if ($category_id !== null) {
            $query->where('category_id', $category_id);
        }
    }

    public function scopeByEmployees($query, $manager_id)
    {
        $query->whereIn('user_id', User::getEmployees($manager_id)->pluck('id'));
    }

    public function scopeByUser($query, $user_id)
    {
        $query->where('user_id', $user_id);
    }
}

app/Http/Controllers/API/PostController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Requests\StorePostRequest;
use App\Models\Category;
use App\Models\Post;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class PostController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Post::class, 'model');
    }

    public function index(Request $request)
    {
        $query = Post::query()
            ->with(['user', 'category'])
            ->orderByDesc('created_at')
            ->category($request->input('filter.category_id'));

        $user = $request->user();

        if ($user->hasRole('manager')) {
            if ($userId = $request->input('filter.user_id')) {
                $query->byUser($userId);
            } else {
                $query->byEmployees($user->id);
            }
        } else {
            $query->byUser($user->id);
        }

        return new JsonResource([
            'results' => $query->paginate(config('settings.max_per_page')),
            'categories' => Category::orderBy('name')->get()->pluck('name', 'id'),
            'employees' => $user->hasRole('manager') ? User::getEmployees($user->id)->pluck('name', 'id') : [],
        ]);
    }

    public function store(StorePostRequest $request)
    {
        $model = new Post($request->validated());
        $model->user_id = $request->user()->id;
        $model->save();

        if ($request->hasFile('image')) {
            $model->addMediaFromRequest('image')
                ->usingFileName(rand() . '.jpg')
                ->toMediaCollection('image');
        }

        return new JsonResource($model->load('category'));
    }

    public function show(Post $model)
    {
        return new JsonResource($model->load('category'));
    }

    public function update(Request $request, Post $model)
    {
        $model->update($request->validated());

        if ($request->hasFile('image')) {
            $model->addMediaFromRequest('image')
                ->usingFileName(rand() . '.jpg')
                ->toMediaCollection('image');
        }

        return new JsonResource($model->load('category'));
    }

    public function destroy(Post $model)
    {
        $model->delete();

        return new JsonResource(['success' => true]);
    }

    public function removeImage(Post $model)
    {
        $this->authorize('update', $model);

        if ($image = $model->getFirstMedia('image')) {
            $image->delete();
        }

        return new JsonResource(['success' => true]);
    }
}

app/Http/Controllers/API/Public/PostController.php
<?php

namespace App\Http\Controllers\API\Public;

use App\Http\Controllers\Controller;
use App\Http\Resources\PostResource;
use App\Models\Post;

class PostController extends Controller
{
    public function index()
    {
        $query = Post::query()
            ->orderByDesc('created_at')
            ->with(['user', 'category', 'media']);

        return PostResource::collection($query->paginate(config('settings.max_per_page')));
    }

    public function show(Post $model)
    {
        $model->load(['user', 'category', 'media']);

        return new PostResource($model);
    }
}

app/Http/Controllers/Frontend/PostController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Requests\StorePostRequest;
use App\Http\Requests\UpdatePostRequest;
use App\Models\Category;
use App\Models\Post;
use App\Models\User;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Post::class, 'model');
    }

    public function index(Request $request)
    {
        $query = Post::query()
            ->with(['user', 'category'])
            ->orderByDesc('created_at')
            ->category($request->input('filter.category_id'));

        $user = $request->user();

        if ($user->hasRole('manager')) {
            if ($userId = $request->input('filter.user_id')) {
                $query->byUser($userId);
            } else {
                $query->byEmployees($user->id);
            }
        } else {
            $query->byUser($user->id);
        }

        return view('posts.index', [
            'results' => $query->paginate(config('settings.max_per_page')),
            'categories' => Category::orderBy('name')->get()->pluck('name', 'id'),
            'employees' => $user->hasRole('manager') ? User::getEmployees($user->id)->pluck('name', 'id') : [],
        ]);
    }

    public function create()
    {
        return view('posts.form', [
            'model' => new Post(),
            'categories' => Category::orderBy('name')->get()->pluck('name', 'id'),
        ]);
    }

    public function store(StorePostRequest $request)
    {
        $model = new Post($request->validated());
        $model->user_id = $request->user()->id;
        $model->save();

        if ($request->hasFile('image')) {
            $model->addMediaFromRequest('image')
                ->usingFileName(rand() . '.jpg')
                ->toMediaCollection('image');
        }

        return redirect()->route('posts.index')->with('success', 'Post created');
    }

    public function edit(Post $model)
    {
        return view('posts.form', [
            'model' => $model,
            'categories' => Category::orderBy('name')->get()->pluck('name', 'id'),
        ]);
    }

    public function update(UpdatePostRequest $request, Post $model)
    {
        $model->update($request->validated());

        if ($request->hasFile('image')) {
            $model->addMediaFromRequest('image')
                ->usingFileName(rand() . '.jpg')
                ->toMediaCollection('image');
        }

        return redirect()->route('posts.index')->with('success', 'Post updated');
    }

    public function destroy(Request $request, Post $model)
    {
        $model->delete();

        return redirect()->route('posts.index', $request->query())->with('success', 'Post deleted');
    }

    public function removeImage(Post $model)
    {
        $this->authorize('update', $model);

        if ($image = $model->getFirstMedia('image')) {
            $image->delete();
        }

        return redirect()->route('posts.edit', $model)->with('success', 'Image deleted');
    }
}

resources/views/posts/form.blade.php
@extends('layouts.app')

@section('content')
    {{ aire()->resourceful($model, 'posts')->encType('multipart/form-data') }}
        <div class="card">
            <h5 class="card-header">Post</h5>
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        {{ aire()->input('title', 'Title')}}
                    </div>
                    <div class="col-6">
                        {{ aire()->select($categories, 'category_id', 'Category')}}
                        {{ aire()->file('image', 'Image') }}
                        @if($model->exists)
                            @if($image = $model->getFirstMediaUrl('image', 'sm'))
                                <div class="mt-3">
                                    <a href="{{ $model->getFirstMediaUrl('image', 'md') }}" class="strip">
                                        <img src="{{ $image }}" alt="{{ $model->title }}" class="img-thumbnail">
                                    </a>
                                </div>
                                <a href="{{ route('posts.remove_image', $model) }}" data-action="post-with-confirm"><small>remove image</small></a>
                            @endif
                        @endif
                    </div>
                </div>
            </div>
            <div class="card-footer pt-3 pb-3">
                <button class="btn btn-primary">{{ $model->exists ? 'Save' : 'Create' }}</button>
                <a href="{{ route('posts.index') }}" class="btn btn-outline-secondary">Back to list</a>
            </div>
        </div>
    {{ aire()->close() }}
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card mb-3">
        <div class="card-body pb-0">
            {{ aire()->open()->route('posts.index')->bind(['filter' => request('filter')]) }}
                <div class="row">
                    <div class="col-3">
                        {{ aire()->select($categories, 'filter[category_id]')->prependEmptyOption('- Select Category -') }}
                    </div>
                    @hasrole('manager')
                        <div class="col-3">
                            {{ aire()->select($employees, 'filter[user_id]')->prependEmptyOption('- Select Employee -') }}
                        </div>
                    @endif
                    <div class="col">
                        <button class="btn btn-secondary">Filter</button>
                        @if(request()->has('filter'))
                            <a href="{{ route('posts.index') }}" class="btn btn-primary">Reset Filter</a>
                        @endif
                        @can('create', \App\Models\Post::class)
                            <a href="{{ route('posts.create') }}" class="btn btn-secondary float-end">Create New Post</a>
                        @endcan
                    </div>
                </div>
            {{ aire()->close() }}
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            Posts
        </div>
        @if($results->total())
            <table class="table table-striped table-hover mb-0 align-middle">
                <thead>
                    <tr>
                        <th>Title</th>
                        @if(auth()->user()->hasRole('manager'))
                            <th>Employee</th>
                        @endif
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($results as $item)
                        <tr>
                            <td>
                                @if($image = $item->getFirstMediaUrl('image', 'xs'))
                                    <a href="{{ $item->getFirstMediaUrl('image', 'md') }}" class="strip float-end">
                                        <img src="{{ $item->getFirstMediaUrl('image', 'xs') }}" alt="{{ $item->title }}" class="img-thumbnail">
                                    </a>
                                @endif
                                <a href="{{ route('posts.edit', $item) }}"><b>{{ $item->title }}</b></a>
                                @if($item->category->exists)
                                    <div>
                                        <small>Category: <a href="{{ route('posts.index', ['filter' => ['category_id' => $item->category->id] + request('filter', [])]) }}">{{ $item->category->name }}</a></small>
                                    </div>
                                @endif
                                <div>
                                    <small class="text-muted">{{ $item->created_at->toDateTimeString() }}</small>
                                </div>
                            </td>
                            @hasrole('manager')
                                <td>
                                    <a href="{{ route('posts.index', ['filter' => ['user_id' => $item->user->id] + request('filter', [])]) }}">{{ $item->user->name }}</a>
                                    <br>
                                    <small class="text-muted">{{ $item->user->email }}</small>
                                </td>
                            @endhasrole
                            <td>
                                <div class="text-nowrap text-end">
                                    @if($item->user_id == auth()->id())
                                        <a href="{{ route('posts.edit', $item) }}" class="btn btn-sm btn-primary">Edit</a>
                                    @endif
                                    <a href="{{ route('posts.destroy', ['model' => $item] + request()->all()) }}" class="btn btn-sm btn-danger" data-action="destroy">Delete</a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            @if($results->hasPages())
                <div class="card-footer clearfix">
                    {{ $results->withQueryString()->links() }}
                </div>
            @endif
        @else
            <div class="card-body">
                <div class="alert alert-danger mb-0">Nothing to show</div>
            </div>
        @endif
    </div>
@endsection