routes/web.php
<?php

use App\Http\Controllers\Frontend\CategoryController;
use App\Http\Controllers\Frontend\EmployeeController;
use App\Http\Controllers\Frontend\PostController;
use Illuminate\Support\Facades\Route;

Auth::routes([
    'reset' => false,
    'confirm' => false,
]);

Route::middleware(['auth:web', 'role:manager|employee'])->group(function () {
    Route::get('/', [PostController::class, 'index'])->name('main');
    Route::post('/posts/{model}/remove-image', [PostController::class, 'removeImage'])->name('posts.remove_image');
    Route::resource('/posts', PostController::class)->except('show')->parameter('posts', 'model');

    Route::resource('/categories', CategoryController::class)->except('show')->parameter('categories', 'model');

    Route::middleware('role:manager')->group(function () {
        Route::resource('/employees', EmployeeController::class)->except('show')->parameter('employees', 'model');
    });
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $fillable = ['name'];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/API/CategoryController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Category::class, 'model');
    }

    public function index(Request $request)
    {
        $user = $request->user();

        $query = Category::query()
            ->withCount(['posts' => function (Builder $query) use ($user) {
                if ($user->hasRole('manager')) {
                    $query->whereIn('user_id', $user->employees->pluck('id'));
                } else {
                    $query->where('user_id', $user->id);
                }
            }])
            ->orderBy('name');

        return new JsonResource(['results' => $query->get()]);
    }

    public function store(CategoryRequest $request)
    {
        $model = Category::create($request->validated());

        return new JsonResource($model);
    }

    public function update(CategoryRequest $request, Category $model)
    {
        $model->update($request->validated());

        return new JsonResource($model);
    }

    public function destroy(Category $model)
    {
        $model->delete();


    }
}

app/Http/Controllers/Frontend/CategoryController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Category::class, 'model');
    }

    public function index(Request $request)
    {
        $user = $request->user();

        $query = Category::query()
            ->withCount(['posts' => function (Builder $query) use ($user) {
                if ($user->hasRole('manager')) {
                    $query->whereIn('user_id', $user->employees->pluck('id'));
                } else {
                    $query->where('user_id', $user->id);
                }
            }])
            ->orderBy('name');

        return view('categories.index', ['results' => $query->get()]);
    }

    public function create()
    {
        return view('categories.form', ['model' => new Category()]);
    }

    public function store(CategoryRequest $request)
    {
        Category::create($request->validated());

        return redirect()->route('categories.index')->with('success', 'Category created');
    }

    public function edit(Category $model)
    {
        return view('categories.form', ['model' => $model]);
    }

    public function update(CategoryRequest $request, Category $model)
    {
        $model->update($request->validated());

        return redirect()->route('categories.index')->with('success', 'Category updated');
    }

    public function destroy(Category $model)
    {
        $model->delete();

        return redirect()->route('categories.index')->with('success', 'Category deleted');
    }
}

resources/views/categories/form.blade.php
@extends('layouts.app')

@section('content')
    {{ aire()->resourceful($model, 'categories') }}
        <div class="card">
            <h5 class="card-header">Category</h5>
            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        {{ aire()->input('name', 'Name')}}
                    </div>
                </div>
            </div>
            <div class="card-footer pt-3 pb-3">
                <button class="btn btn-primary">{{ $model->exists ? 'Save' : 'Create' }}</button>
                <a href="{{ route('categories.index') }}" class="btn btn-outline-secondary">Back to list</a>
            </div>
        </div>
    {{ aire()->close() }}
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
    @can('create', \App\Models\Category::class)
        <div class="mb-3">
            <a href="{{ route('categories.create') }}" class="btn btn-secondary">Create New Category</a>
        </div>
    @endcan
    <div class="card">
        <div class="card-header">
            Categories
        </div>
        @if($results)
            <table class="table table-striped table-hover mb-0">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>{{ auth()->user()->hasRole('manager') ? 'Posts by your employees' : 'Your posts' }}</th>
                        @can(['update', 'delete'], \App\Models\Category::class)
                            <th></th>
                        @endcan
                    </tr>
                </thead>
                <tbody>
                @foreach($results as $item)
                    <tr>
                        <td>
                            <a href="{{ route('posts.index', ['filter' => ['category_id' => $item->id]]) }}">{{ $item->name }}</a>
                        </td>
                        <td>
                            <a href="{{ route('posts.index', ['filter' => ['category_id' => $item->id]]) }}" title="Post count" data-toggle="tooltip"><small class="badge bg-secondary">{{ $item->posts_count }}</small></a>
                        </td>
                        @can(['update', 'delete'], \App\Models\Category::class)
                            <td>
                                <div class="text-nowrap text-end">
                                    @can('update', \App\Models\Category::class)
                                        <a href="{{ route('categories.edit', $item) }}" class="btn btn-sm btn-primary">Edit</a>
                                    @endcan
                                    @can('delete', \App\Models\Category::class)
                                        <a href="{{ route('categories.destroy', $item) }}" class="btn btn-sm btn-danger" data-action="destroy">Delete</a>
                                    @endcan
                                </div>
                            </td>
                        @endcan
                    </tr>
                @endforeach
                </tbody>
            </table>
        @else
            <div class="card-body">
                <div class="alert alert-danger mb-0">Nothing to show</div>
            </div>
        @endif
    </div>
@endsection