routes/web.php
<?php

use App\Http\Controllers\Frontend\CategoryController;
use App\Http\Controllers\Frontend\EmployeeController;
use App\Http\Controllers\Frontend\PostController;
use Illuminate\Support\Facades\Route;

Auth::routes([
    'reset' => false,
    'confirm' => false,
]);

Route::middleware(['auth:web', 'role:manager|employee'])->group(function () {
    Route::get('/', [PostController::class, 'index'])->name('main');
    Route::post('/posts/{model}/remove-image', [PostController::class, 'removeImage'])->name('posts.remove_image');
    Route::resource('/posts', PostController::class)->except('show')->parameter('posts', 'model');

    Route::resource('/categories', CategoryController::class)->except('show')->parameter('categories', 'model');

    Route::middleware('role:manager')->group(function () {
        Route::resource('/employees', EmployeeController::class)->except('show')->parameter('employees', 'model');
    });
});

app/Http/Controllers/API/EmployeeController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class EmployeeController extends Controller
{
    public function index(Request $request)
    {
        $query = User::query()
            ->orderByDesc('created_at')
            ->employees($request->user()->id);

        return new JsonResource(['results' => $query->paginate(config('settings.max_per_page'))]);
    }

    public function store(StoreUserRequest $request)
    {
        $model = User::create($request->validated() + ['manager_id' => $request->user()->id]);

        return new JsonResource($model);
    }

    public function update(UpdateUserRequest $request, User $model)
    {
        $model->name = $request->validated('name');
        $model->email = $request->validated('email');
        if ($request->validated('password')) {
            $model->password = \Hash::make($request->validated('password'));
        }
        $model->save();

        return new JsonResource($model);
    }

    public function destroy(User $model)
    {
        $model->delete();

        return new JsonResource(['success' => true]);
    }
}

app/Http/Controllers/Frontend/EmployeeController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\User;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    public function index(Request $request)
    {
        $query = User::query()
            ->orderByDesc('created_at')
            ->employees($request->user()->id);

        return view('employees.index', ['results' => $query->paginate(config('settings.max_per_page'))]);
    }

    public function create()
    {
        return view('employees.form', ['model' => new User()]);
    }

    public function store(StoreUserRequest $request)
    {
        User::create($request->validated() + ['manager_id' => $request->user()->id]);

        return redirect()->route('employees.index')->with('success', 'Employee created');
    }

    public function edit(User $model)
    {
        return view('employees.form', ['model' => $model]);
    }

    public function update(UpdateUserRequest $request, User $model)
    {
        $model->name = $request->validated('name');
        $model->email = $request->validated('email');
        if ($request->validated('password')) {
            $model->password = \Hash::make($request->validated('password'));
        }
        $model->save();

        return redirect()->route('employees.index')->with('success', 'Employee updated');
    }

    public function destroy(User $model)
    {
        $model->delete();

        return redirect()->route('employees.index')->with('success', 'Employee deleted');
    }
}

resources/views/employees/form.blade.php
@extends('layouts.app')

@section('content')
    {{ aire()->resourceful($model, 'employees') }}
        <div class="card">
            <h5 class="card-header">Employee</h5>
            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        {{ aire()->input('name', 'Name')}}
                        {{ aire()->input('email', 'Email')}}
                        {{ aire()->password('password', 'Password')->value('') }}
                        {{ aire()->password('password_confirmation', 'Password confirmation')->value('') }}
                    </div>
                </div>
            </div>
            <div class="card-footer pt-3 pb-3">
                <button class="btn btn-primary">{{ $model->exists ? 'Save' : 'Create' }}</button>
                <a href="{{ route('employees.index') }}" class="btn btn-outline-secondary">Back to list</a>
            </div>
        </div>
    {{ aire()->close() }}
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="mb-3">
        <a href="{{ route('employees.create') }}" class="btn btn-secondary">Create New Employee</a>
    </div>
    <div class="card">
        <div class="card-header">
            Employees
        </div>
        @if($results->total())
            <table class="table table-striped table-hover mb-0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                @foreach($results as $item)
                    <tr>
                        <td>
                            <a href="{{ route('employees.edit', $item) }}">{{ $item->name }}</a>
                        </td>
                        <td>
                            <small>{{ $item->email }}</small>
                        </td>
                        <td>
                            <div class="text-nowrap text-end">
                                <a href="{{ route('employees.edit', $item) }}" class="btn btn-sm btn-primary">Edit</a>
                                <a href="{{ route('employees.destroy', $item) }}" class="btn btn-sm btn-danger" data-action="destroy">Delete</a>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            @if($results->hasPages())
                <div class="card-footer clearfix">
                    {{ $results->withQueryString()->links() }}
                </div>
            @endif
        @else
            <div class="card-body">
                <div class="alert alert-danger mb-0">Nothing to show</div>
            </div>
        @endif
    </div>
@endsection